
name: build
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '6.0.x'

      - name: Install Python Tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install yaclog yaclog-ksp

      - name: Download Dependencies
        working-directory: Source
        run: |
          wget --user drewcassidy --password ${{ secrets.PILE_OF_ROCKS_PASS }} https://pileof.rocks/Secret/conformal-decals-dependencies-1.zip
          unzip conformal-decals-dependencies-*.zip -d ConformalDecals/dlls
          dotnet build --configuration Release ConformalDecals.sln
          
      - name: Build DLL
        working-directory: Source
        run: |
          mkdir -p ../GameData/ConformalDecals/Plugins
          dotnet build --configuration Release ConformalDecals.sln
          
      - name: Upload Unbundled Build
        uses: actions/upload-artifact@v3
        with:
          name: build-unbundled
          path: |
            GameData/ConformalDecals 
            README.md 
            CHANGELOG.md 
            LICENSE-ART.md 
            LICENSE-SOURCE.md